# action.yml
name: 'Hello Action'
description: 'The Action Docker'
inputs:
  config-prefix:  # id of input
    description: 'config prefix to test'
    required: true
    default: '7nodes'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config-prefix }}