# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master, action-time ]
  pull_request:
    branches: [ master, action-time ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install latest version of Kind
        run: |
          GO111MODULE=on go get sigs.k8s.io/kind
      - name: Create Kind cluster
        run: |
          PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config kind-config.yaml
      - name: Run some sanity checks
        # kubectl is already installed on the Github Ubuntu worker
        run: |
          kubectl get nodes -o wide
          kubectl get pods --all-namespaces -o wide
          kubectl get services --all-namespaces -o wid
    # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
         echo current dir $PWD
